# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27a20d3141d8b3696fb6aa6abdd4b4cc788f9ef01764bbb766c537a4735c14371cead1b193edd713767d5f92cb2fd3f4e961705786d3ac2af63978e7d9811ff

test:
  secret_key_base: 50d440bcf7490a82d12c21a9017404eb5d9d0d21232f0e32e5ccb76830200cc20f233af76b6db0f47cb65256d32314e4a068b663a220a859f0533dd6b6abd17a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
